#Utilize a task Replace Tokens para substituir os valores 
# . versaodotnet: Versao do .Net (core): 
# . nomeapp: nome da aplicacao

FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:__versaodotnet__-alpine
WORKDIR /var/wwroot/__nomeapp__

#Adiciona usuario do Container (Non Root)
RUN adduser -D app 
EXPOSE 8080
EXPOSE 8443
ENV ASPNETCORE_URLS="http://+:8080"

#Copia cod. fonte e CA 
COPY . .
COPY CA.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates &&  chown app -R .

#Usuario que rodara o container
USER app
ENTRYPOINT ["dotnet", "__nomeapp__.dll"]